import React, { useState } from 'react';
import { AIPriorityRecommendation } from '../../types';
import { PriorityBadge, CategoryBadge } from '../common/Badge';
import { apiService } from '../../services/api';
import { useApp } from '../../context/AppContext';
import {
  X,
  Sparkles,
  DollarSign,
  Calendar,
  Building,
  Target,
  CheckCircle2,
  AlertTriangle,
  Quote,
  Layers,
  FileText,
  Printer,
  ChevronDown,
  ChevronUp,
  Download,
  ShieldCheck,
  Info
} from 'lucide-react';

interface RecommendationModalProps {
  rec: AIPriorityRecommendation;
  onClose: () => void;
}

export const RecommendationModal: React.FC<RecommendationModalProps> = ({ rec, onClose }) => {
  const { setLiveNotification, refreshData } = useApp();

  const [currentStatus, setCurrentStatus] = useState<string>(rec.status);
  const [isUpdating, setIsUpdating] = useState<boolean>(false);
  const [showFactors, setShowFactors] = useState<boolean>(true);

  const handleStatusChange = async (newStatus: string) => {
    setIsUpdating(true);
    try {
      await apiService.updateRecommendationStatus(rec.recommendation_id, newStatus);
      setCurrentStatus(newStatus);
      setLiveNotification({
        message: `Recommendation status updated to "${newStatus}"`,
        type: 'success'
      });
      await refreshData();
    } catch (err) {
      console.error('Failed to update status:', err);
    } finally {
      setIsUpdating(false);
    }
  };

  const handleExportBrief = () => {
    const briefContent = `
CIVICPULSE AI — PUBLIC INFRASTRUCTURE DECISION BRIEF
=====================================================
Title: ${rec.title}
Region: ${rec.district}, ${rec.state} (${rec.country})
Category: ${rec.category} -> ${rec.subcategory}
Priority Assessment: ${rec.priority_score}/100 (${rec.priority_level})
Verified Citizen Requests: ${rec.citizen_requests_count}
Estimated Affected Population: ~${rec.affected_population_estimate.toLocaleString()}
Existing Infrastructure Capacity Index: ${rec.infrastructure_index_score}/100

EVIDENCE & PLANNING JUSTIFICATION:
${rec.ai_reasoning}

SUGGESTED PUBLIC INTERVENTION:
Project Title: ${rec.suggested_intervention.project_title}
Applicable Public Scheme: ${rec.suggested_intervention.scheme_name}
Estimated Budget Outlay: INR ${rec.suggested_intervention.estimated_cost_inr_cr} Cr (USD $${rec.suggested_intervention.estimated_cost_usd_m}M)
Estimated Implementation Timeline: ${rec.suggested_intervention.estimated_timeline_months} Months
Implementing Public Agency: ${rec.suggested_intervention.implementation_agency}
UN SDG Alignment: ${rec.suggested_intervention.sdg_alignment.join(', ')}

KEY DELIVERABLES:
${rec.suggested_intervention.key_deliverables.map(d => `- ${d}`).join('\n')}

Generated by CivicPulse AI Digital Public Good Platform
=====================================================
    `.trim();

    const blob = new Blob([briefContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Policy_Brief_${rec.recommendation_id}_${rec.district}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 sm:p-6 animate-fadeIn">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xl max-w-4xl w-full max-h-[92vh] flex flex-col overflow-hidden">
        {/* Modal Top Header */}
        <div className="p-6 border-b border-slate-200 flex items-start justify-between gap-4 bg-slate-50/80">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-200">
                {rec.recommendation_id}
              </span>
              <CategoryBadge category={rec.category} />
              <PriorityBadge level={rec.priority_level} score={rec.priority_score} size="sm" />
            </div>

            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight">
              {rec.title}
            </h2>

            <div className="flex items-center gap-3 text-xs text-slate-500 font-medium">
              <span>{rec.district}, {rec.state} ({rec.country})</span>
              <span>•</span>
              <span>Regional Demographics ID: {rec.region_id}</span>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-lg bg-slate-200/70 hover:bg-slate-300 text-slate-700 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs text-slate-700 divide-y divide-slate-100">
          {/* Section 1: Why This Requires Attention */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
              <Sparkles className="w-4 h-4 text-blue-600" />
              <span>Evidence-Based Planning Justification</span>
            </div>

            <p className="text-xs text-slate-700 leading-relaxed font-normal bg-slate-50 p-4 rounded-xl border border-slate-200">
              {rec.ai_reasoning}
            </p>

            {/* Quick Metrics Bar */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
                <span className="text-[10px] text-slate-400 uppercase font-semibold block">Citizen Demand</span>
                <span className="text-sm font-bold font-mono text-slate-900 mt-0.5 block">
                  {rec.citizen_requests_count.toLocaleString()} Signals
                </span>
              </div>

              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
                <span className="text-[10px] text-slate-400 uppercase font-semibold block">Affected Population</span>
                <span className="text-sm font-bold font-mono text-slate-900 mt-0.5 block">
                  ~{rec.affected_population_estimate.toLocaleString()} Residents
                </span>
              </div>

              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
                <span className="text-[10px] text-slate-400 uppercase font-semibold block">Capacity Index</span>
                <span className="text-sm font-bold font-mono text-rose-600 mt-0.5 block">
                  {rec.infrastructure_index_score.toFixed(0)} / 100
                </span>
              </div>

              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
                <span className="text-[10px] text-slate-400 uppercase font-semibold block">Active Matching Works</span>
                <span className="text-sm font-bold font-mono text-slate-900 mt-0.5 block">
                  {rec.existing_matching_projects_count} Projects
                </span>
              </div>
            </div>
          </div>

          {/* Section 2: Interactive 5-Factor Score Breakdown */}
          <div className="pt-6 space-y-3">
            <div
              onClick={() => setShowFactors(!showFactors)}
              className="flex items-center justify-between cursor-pointer select-none"
            >
              <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
                <Layers className="w-4 h-4 text-blue-600" />
                <span>Explainable Priority Score Breakdown ({rec.priority_score}/100)</span>
              </div>
              <span className="text-blue-600 text-xs font-semibold flex items-center gap-1">
                {showFactors ? 'Hide Weights' : 'Show Weights'}
                {showFactors ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              </span>
            </div>

            {showFactors && (
              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3 animate-fadeIn">
                <p className="text-[11px] text-slate-500">
                  Priority scores are mathematically calculated from 5 transparent factors with fixed weights:
                </p>

                <div className="space-y-2.5">
                  <div>
                    <div className="flex items-center justify-between text-xs font-medium text-slate-700 mb-1">
                      <span>Citizen Demand Intensity (30% weight)</span>
                      <span className="font-mono font-bold">{rec.factor_breakdown.citizen_demand_score}/100</span>
                    </div>
                    <div className="w-full bg-slate-200 rounded-full h-1.5">
                      <div className="bg-blue-600 h-1.5 rounded-full" style={{ width: `${rec.factor_breakdown.citizen_demand_score}%` }} />
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between text-xs font-medium text-slate-700 mb-1">
                      <span>Infrastructure Capacity Deficit (25% weight)</span>
                      <span className="font-mono font-bold">{rec.factor_breakdown.infrastructure_gap_score}/100</span>
                    </div>
                    <div className="w-full bg-slate-200 rounded-full h-1.5">
                      <div className="bg-rose-600 h-1.5 rounded-full" style={{ width: `${rec.factor_breakdown.infrastructure_gap_score}%` }} />
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between text-xs font-medium text-slate-700 mb-1">
                      <span>Vulnerable Population Impact (20% weight)</span>
                      <span className="font-mono font-bold">{rec.factor_breakdown.population_impact_score}/100</span>
                    </div>
                    <div className="w-full bg-slate-200 rounded-full h-1.5">
                      <div className="bg-indigo-600 h-1.5 rounded-full" style={{ width: `${rec.factor_breakdown.population_impact_score}%` }} />
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between text-xs font-medium text-slate-700 mb-1">
                      <span>Severity & Urgency Assessment (15% weight)</span>
                      <span className="font-mono font-bold">{rec.factor_breakdown.severity_urgency_score}/100</span>
                    </div>
                    <div className="w-full bg-slate-200 rounded-full h-1.5">
                      <div className="bg-amber-600 h-1.5 rounded-full" style={{ width: `${rec.factor_breakdown.severity_urgency_score}%` }} />
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between text-xs font-medium text-slate-700 mb-1">
                      <span>Development Alignment & Project Deficit (10% weight)</span>
                      <span className="font-mono font-bold">{rec.factor_breakdown.project_deficit_score}/100</span>
                    </div>
                    <div className="w-full bg-slate-200 rounded-full h-1.5">
                      <div className="bg-emerald-600 h-1.5 rounded-full" style={{ width: `${rec.factor_breakdown.project_deficit_score}%` }} />
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Section 3: Suggested Public Intervention Specification */}
          <div className="pt-6 space-y-3">
            <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
              <Building className="w-4 h-4 text-blue-600" />
              <span>Suggested Public Works Intervention Blueprint</span>
            </div>

            <div className="bg-white p-4 rounded-xl border border-slate-200 space-y-3 shadow-2xs">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-2">
                <span className="font-bold text-slate-900 text-sm">
                  {rec.suggested_intervention.project_title}
                </span>
                <span className="text-[11px] font-semibold text-blue-800 bg-blue-50 px-2.5 py-0.5 rounded border border-blue-200">
                  {rec.suggested_intervention.scheme_name}
                </span>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
                <div>
                  <span className="text-[10px] text-slate-400 uppercase font-semibold block">Estimated Budget</span>
                  <span className="font-bold text-slate-900 font-mono text-sm">
                    ₹{rec.suggested_intervention.estimated_cost_inr_cr} Cr
                  </span>
                  <span className="text-[10px] text-slate-400 block font-mono">(${rec.suggested_intervention.estimated_cost_usd_m}M USD)</span>
                </div>

                <div>
                  <span className="text-[10px] text-slate-400 uppercase font-semibold block">Target Timeline</span>
                  <span className="font-bold text-slate-900 font-mono text-sm">
                    {rec.suggested_intervention.estimated_timeline_months} Months
                  </span>
                </div>

                <div className="col-span-2">
                  <span className="text-[10px] text-slate-400 uppercase font-semibold block">Implementing Public Agency</span>
                  <span className="font-semibold text-slate-800">
                    {rec.suggested_intervention.implementation_agency}
                  </span>
                </div>
              </div>

              {/* Key Deliverables */}
              <div>
                <span className="text-[10px] text-slate-500 uppercase font-bold block mb-1.5">
                  Key Deliverables:
                </span>
                <ul className="space-y-1 text-slate-600 list-disc list-inside">
                  {rec.suggested_intervention.key_deliverables.map((item, idx) => (
                    <li key={idx}>{item}</li>
                  ))}
                </ul>
              </div>

              {/* SDG Alignment */}
              <div className="flex items-center gap-1.5 flex-wrap pt-2 border-t border-slate-100">
                <span className="text-[10px] text-slate-400 uppercase font-bold mr-1">UN SDG Goals:</span>
                {rec.suggested_intervention.sdg_alignment.map((sdg, idx) => (
                  <span key={idx} className="text-[10px] font-semibold bg-slate-100 text-slate-700 px-2 py-0.5 rounded border border-slate-200">
                    {sdg}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Section 4: Verbatim Citizen Voice Feedback */}
          <div className="pt-6 space-y-3">
            <div className="flex items-center gap-2 font-bold text-slate-900 text-sm">
              <Quote className="w-4 h-4 text-blue-600" />
              <span>Verbatim Multilingual Citizen Voice Signals</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {rec.sample_citizen_quotes.map((q) => (
                <div key={q.request_id} className="bg-slate-50 p-3.5 rounded-lg border border-slate-200 space-y-1.5">
                  <div className="flex items-center justify-between text-[10px] text-slate-400 border-b border-slate-200 pb-1">
                    <span className="font-semibold text-slate-700">{q.locality}</span>
                    <span className="font-mono">{q.language}</span>
                  </div>
                  <div className="text-slate-800 text-[11px] leading-relaxed italic">
                    "{q.raw_text}"
                  </div>
                  <div className="text-[10px] text-slate-500 font-medium">
                    <span className="text-slate-400">Translated:</span> "{q.translated_text}"
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 sm:p-5 border-t border-slate-200 bg-slate-50 flex flex-col sm:flex-row items-center justify-between gap-3">
          {/* Status Changer */}
          <div className="flex items-center gap-2 w-full sm:w-auto">
            <span className="text-xs font-semibold text-slate-600">Review Decision:</span>
            <select
              value={currentStatus}
              onChange={(e) => handleStatusChange(e.target.value)}
              disabled={isUpdating}
              className="text-xs font-semibold bg-white border border-slate-300 rounded-lg p-1.5 text-slate-900 focus:ring-2 focus:ring-blue-600 focus:outline-hidden cursor-pointer"
            >
              <option value="Under Policy Review">Under Policy Review</option>
              <option value="Approved for DPR Preparation">Approved for DPR Preparation</option>
              <option value="Recommended for Next Budget Cycle">Recommended for Next Budget Cycle</option>
              <option value="Pending Site Inspection">Pending Site Inspection</option>
            </select>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
            <button
              onClick={handleExportBrief}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-white hover:bg-slate-100 border border-slate-300 text-slate-700 text-xs font-semibold transition-all cursor-pointer shadow-2xs"
            >
              <Download className="w-3.5 h-3.5 text-slate-500" />
              <span>Export Policy Brief</span>
            </button>

            <button
              onClick={onClose}
              className="px-5 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition-all cursor-pointer shadow-2xs"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
